#!/bin/bash
set -e

p1=http://192.168.198.1:19666
p2=http://192.168.198.1:7890
p3=socks5://192.168.198.1:7891

p=$p1


if [ -z "$p" ]
then
      echo "proxy is empty"
      find . -type f -exec sed -i '/aliyun/d' {} \;
      find . -type f -exec sed -i '/GOPROXY/d' {} \;
      find . ! -name "build" -type f -exec sed -i '/git    config/d' {} \;
else
      echo "proxy is NOT empty"
fi

export http_proxy=$p
export https_proxy=$p
export HTTP_PROXY=$p
export HTTPS_PROXY=$p
make




# git config --global --unset http.proxy
# git config --global http.sslVerify false
# git config --global http.proxy   $p1
# git config --global https.proxy  $p1
