#!/bin/bash
set -e -x

source $(dirname $0)/version

cd $(dirname $0)/..

mkdir -p build

bash -x ./scripts/build

ID=$(docker run --net=host --privileged --rm -itd $REPO/platos-iso:$TAG)
docker attach $ID || docker kill $ID
